/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import com.sun.corba.se.impl.activation.ServerMain;
import domen.Menadzer;
import forme.grupe.PretraziGrupe;
import forme.kursevi.PretraziKurseve;
import forme.predavaci.PretraziPredavace;
import forme.ucesnici.DodajIzmeniUcesnika;
import forme.ucesnici.PretraziUcesnike;
import java.util.logging.Level;
import java.util.logging.Logger;
import kontroler.Kontroler;

/**
 *
 * @author hp
 */
public class GlavnaFrm extends javax.swing.JFrame {
private Menadzer ulogovan;
    /**
     * Creates new form GlavnaFrm
     */
    public GlavnaFrm() {
       initComponents();
         setLocationRelativeTo(null);
    }
    
     public GlavnaFrm(Menadzer ulogovan) {
        initComponents();     
        this.ulogovan = ulogovan;
        lblKorisnik.setText("Ulogovani ste kao : "+ulogovan);
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKorisnik = new javax.swing.JLabel();
        btnUcesnici = new javax.swing.JButton();
        btnPredavaci = new javax.swing.JButton();
        btnGrupe = new javax.swing.JButton();
        btnKursevi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        stavkaMenijaIzlogujSe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblKorisnik.setText("Korisnik");

        btnUcesnici.setText("Učesnici");
        btnUcesnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcesniciActionPerformed(evt);
            }
        });

        btnPredavaci.setText("Predavači");
        btnPredavaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPredavaciActionPerformed(evt);
            }
        });

        btnGrupe.setText("Grupe");
        btnGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupeActionPerformed(evt);
            }
        });

        btnKursevi.setText("Kursevi");
        btnKursevi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurseviActionPerformed(evt);
            }
        });

        stavkaMenijaIzlogujSe.setText("Izloguj se");
        stavkaMenijaIzlogujSe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stavkaMenijaIzlogujSeMouseClicked(evt);
            }
        });
        stavkaMenijaIzlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stavkaMenijaIzlogujSeActionPerformed(evt);
            }
        });
        jMenuBar1.add(stavkaMenijaIzlogujSe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKorisnik)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPredavaci, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUcesnici, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKursevi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(136, 136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblKorisnik)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUcesnici)
                    .addComponent(btnKursevi))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPredavaci)
                    .addComponent(btnGrupe))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUcesniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcesniciActionPerformed
        PretraziUcesnike pu=new PretraziUcesnike(this,ulogovan);
        pu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUcesniciActionPerformed

    private void btnPredavaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPredavaciActionPerformed
        PretraziPredavace fpp=new PretraziPredavace(this,ulogovan);
        fpp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPredavaciActionPerformed

    private void btnKurseviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurseviActionPerformed
        PretraziKurseve pk=new PretraziKurseve(this,ulogovan);
        pk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKurseviActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
          izlogujSe();
    }//GEN-LAST:event_formWindowClosing

    private void stavkaMenijaIzlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stavkaMenijaIzlogujSeActionPerformed
       
    }//GEN-LAST:event_stavkaMenijaIzlogujSeActionPerformed

    private void stavkaMenijaIzlogujSeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stavkaMenijaIzlogujSeMouseClicked
         izlogujSe();
        Login login=new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stavkaMenijaIzlogujSeMouseClicked

    private void btnGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupeActionPerformed
       PretraziGrupe pg=new PretraziGrupe(this, ulogovan);
       pg.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnGrupeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrupe;
    private javax.swing.JButton btnKursevi;
    private javax.swing.JButton btnPredavaci;
    private javax.swing.JButton btnUcesnici;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblKorisnik;
    private javax.swing.JMenu stavkaMenijaIzlogujSe;
    // End of variables declaration//GEN-END:variables
  private void izlogujSe() {
         try {
            Kontroler.vratiInstancu().izlogujMenadzera(ulogovan);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


}
