/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.grupe;

import domen.AbstractObjekat;
import domen.Grupa;
import domen.GrupaStavkaDodatiPredavaci;
import domen.GrupaStavkaDodatiUcesnici;
import domen.Kurs;
import domen.Menadzer;
import domen.Predavac;
import domen.Ucesnik;
import exception.ValidacijaException;
import forme.GlavnaFrm;
import forme.kursevi.PretraziKurseve;
import forme.predavaci.DodajIzmeniPredavaca;
import forme.ucesnici.DodajIzmeniUcesnika;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.runtime.ListAdapter;
import kontroler.Kontroler;
import model.ModelTabeleGrupe;
import model.ModelTabelePredavaci;
import model.ModelTabeleStavkePredavaci;
import model.ModelTabeleStavkeUcesnici;
import model.ModelTabeleUcesnici;

/**
 *
 * @author hp
 */
public class DodajIzmeniGrupe extends javax.swing.JFrame {

    JFrame glavna;
    String status;
    Grupa grupa;
    Menadzer ulogovaniMenadzer;

    //tabele za vrstu stavke
    ModelTabelePredavaci mtpredavaci;
    ModelTabeleUcesnici mtucesnici;

    //tabele za stavke
    ModelTabeleStavkePredavaci mtstavkepredavaci; 
    ModelTabeleStavkeUcesnici mtstavkeucesnici;

    /**
     * Creates new form DodajIzmeniGrupe
     */
    public DodajIzmeniGrupe() {
        initComponents();
          setLocationRelativeTo(null);
    }

    public DodajIzmeniGrupe(JFrame glavna, Menadzer ulogovaniMenadzer) {
        initComponents();
        this.ulogovaniMenadzer = ulogovaniMenadzer;
        this.glavna = glavna;
        this.setTitle("Unos grupe");

        grupa = new Grupa(0, null, new Date(), null, ulogovaniMenadzer); 

        popuniTabeluPredavaci();
        popuniTabeluUcesnici();
        this.status = "unos";
        popuniCBKursevi();
        srediTabelu();
        srediFormu();
          setLocationRelativeTo(null);

    }

    public DodajIzmeniGrupe(JFrame forma, Menadzer ulogovaniMenadzer, Grupa grupa) {
        initComponents();
        this.ulogovaniMenadzer = ulogovaniMenadzer;
        this.setTitle("Izmena grupe");
        this.glavna = forma;
        this.status = "izmena";
        txtNaziv.setText(grupa.getNaziv());
        popuniTabeluPredavaci();
        popuniTabeluUcesnici();

        popuniCBKursevi();

        this.grupa = grupa;
        srediTabelu();
        srediFormu(grupa);
          setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtDatumOd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPredavaci = new javax.swing.JTable();
        txtDodajPredavača = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDodatiPredavaci = new javax.swing.JTable();
        btnObrisiPredavaca = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUcesnici = new javax.swing.JTable();
        btnDodajUcesnika = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDodatiUcesnici = new javax.swing.JTable();
        btnObrisiUcesnika = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbKursevi = new javax.swing.JComboBox<>();
        btnSacuvaj = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtGrupaID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMenadzer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Unesi podatke o grupi:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Datum početka:");

        jLabel5.setText("Izaberi predavača:");

        tblPredavaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPredavaci);

        txtDodajPredavača.setText("Dodaj predavača");
        txtDodajPredavača.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDodajPredavačaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDodajPredavača, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDodajPredavača))
        );

        jLabel6.setText("Dodati predavača:");

        tblDodatiPredavaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDodatiPredavaci);

        btnObrisiPredavaca.setText("Obriši predavača");
        btnObrisiPredavaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPredavacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnObrisiPredavaca)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnObrisiPredavaca))
        );

        jLabel7.setText("Izaberi učesnika:");

        tblUcesnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblUcesnici);

        btnDodajUcesnika.setText("Dodaj učesnika");
        btnDodajUcesnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUcesnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDodajUcesnika)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDodajUcesnika))
        );

        jLabel8.setText("Dodati učesnici:");

        tblDodatiUcesnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDodatiUcesnici);

        btnObrisiUcesnika.setText("Obriši učesnika");
        btnObrisiUcesnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUcesnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnObrisiUcesnika, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnObrisiUcesnika))
        );

        jLabel9.setText("Izaberi kurs:");

        cmbKursevi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKurseviActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        jLabel4.setText("GrupaID:");

        jLabel10.setText("Menadžer:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNaziv)
                            .addComponent(txtDatumOd)
                            .addComponent(cmbKursevi, 0, 178, Short.MAX_VALUE)
                            .addComponent(txtGrupaID)
                            .addComponent(txtMenadzer))
                        .addGap(258, 258, 258)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSacuvaj)
                            .addComponent(btnOdustani))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtGrupaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txtMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbKursevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDodajPredavačaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDodajPredavačaActionPerformed
        int red = tblPredavaci.getSelectedRow();
        if (red != -1) {
            Predavac p = (Predavac) mtpredavaci.getLista().get(red);
            mtstavkepredavaci.dodajStavku(p, grupa);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Izaberite predavača kog želite da dodate!");
        }
    }//GEN-LAST:event_txtDodajPredavačaActionPerformed

    private void btnDodajUcesnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUcesnikaActionPerformed
        int red = tblUcesnici.getSelectedRow();
        if (red != -1) {
            Ucesnik u = (Ucesnik) mtucesnici.getLista().get(red);
            mtstavkeucesnici.dodajStavku(u, grupa);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Izaberite ucesnika kog želite da dodate!");
        }
    }//GEN-LAST:event_btnDodajUcesnikaActionPerformed

    private void btnObrisiPredavacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPredavacaActionPerformed
        int red = tblDodatiPredavaci.getSelectedRow();
        if (red != -1) {
            mtstavkepredavaci.izbaciStavku(red);
            mtstavkepredavaci.postaviRB();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Izaberite predavača kog želite da izbacite!");
        }
    }//GEN-LAST:event_btnObrisiPredavacaActionPerformed

    private void btnObrisiUcesnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUcesnikaActionPerformed
        int red = tblDodatiUcesnici.getSelectedRow();
        if (red != -1) {
            mtstavkeucesnici.izbaciStavku(red);
            mtstavkeucesnici.postaviRB();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Izaberite učesnika kog želite da izbacite!");
        }
    }//GEN-LAST:event_btnObrisiUcesnikaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {

            Kurs kurs = (Kurs) cmbKursevi.getSelectedItem();
            validirajIPostaviVrednosti(kurs);
            Grupa gru;
            if (status.equals("unos")) {
                gru = (Grupa) Kontroler.vratiInstancu().sacuvajGrupu(grupa);
                JOptionPane.showMessageDialog(this, "Uspešno ste sačuvali grupu:\nID: " + gru.getGrupaID() + "\nNaziv grupe: " + gru.getNaziv() + "\nMenadzer: " + gru.getMenadzer().toString(), "Uspešno", JOptionPane.INFORMATION_MESSAGE);
            } else {
                List<AbstractObjekat> listaZaMenjanje = napraviListuPredavaca();
                List<AbstractObjekat> listaZaMenjanje2 = napraviListuUcesnika();

                grupa.setListaPredavaca(mtstavkepredavaci.getLista());
                grupa.setListaUcesnika(mtstavkeucesnici.getLista());

                gru = (Grupa) Kontroler.vratiInstancu().izmeniGrupu(grupa);
                JOptionPane.showMessageDialog(this, "Izmenjena je grupa:\nID: " + gru.getGrupaID() + "\nNaziv grupe: " + gru.getNaziv() + "\nMenadzer: " + gru.getMenadzer().toString(), "Uspešno", JOptionPane.INFORMATION_MESSAGE);
            }
            glavna.setVisible(true);
            this.dispose();
        } catch (ValidacijaException ex) {
            JOptionPane.showMessageDialog(this, "Ne moze da se validira", "Greška", JOptionPane.ERROR_MESSAGE); //ex.message()
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Exception ex", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        PretraziGrupe pg = new PretraziGrupe(glavna, ulogovaniMenadzer);
        pg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void cmbKurseviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKurseviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKurseviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajIzmeniGrupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajIzmeniGrupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajIzmeniGrupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajIzmeniGrupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DodajIzmeniGrupe().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajUcesnika;
    private javax.swing.JButton btnObrisiPredavaca;
    private javax.swing.JButton btnObrisiUcesnika;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> cmbKursevi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDodatiPredavaci;
    private javax.swing.JTable tblDodatiUcesnici;
    private javax.swing.JTable tblPredavaci;
    private javax.swing.JTable tblUcesnici;
    private javax.swing.JTextField txtDatumOd;
    private javax.swing.JButton txtDodajPredavača;
    private javax.swing.JTextField txtGrupaID;
    private javax.swing.JTextField txtMenadzer;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    private void popuniCBKursevi() {

        try {
            List<AbstractObjekat> listaTipova = Kontroler.vratiInstancu().ucitajKurseve();
            cmbKursevi.setModel(new DefaultComboBoxModel(listaTipova.toArray()));
            cmbKursevi.setSelectedItem(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
       

    }

    private void srediFormu() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumOd.setEnabled(false);
        String datum = sdf.format(grupa.getDatumOd());
        txtDatumOd.setText(datum);
        txtGrupaID.setEnabled(false);
        txtMenadzer.setText(grupa.getMenadzer().toString());
        txtMenadzer.setEnabled(false);
        this.ulogovaniMenadzer = ulogovaniMenadzer; //dodato

    }

    private void srediTabelu() {

        mtstavkepredavaci = new ModelTabeleStavkePredavaci();
        mtstavkeucesnici = new ModelTabeleStavkeUcesnici();
        tblDodatiPredavaci.setModel(mtstavkepredavaci);
        tblDodatiUcesnici.setModel(mtstavkeucesnici);
    }

    private void popuniTabeluPredavaci() {
        try {
            List<AbstractObjekat> predavaci = Kontroler.vratiInstancu().ucitajPredavace();
            mtpredavaci = new ModelTabelePredavaci(predavaci);
            tblPredavaci.setModel(mtpredavaci);
        } catch (Exception ex) {
            Logger.getLogger(DodajIzmeniPredavaca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniTabeluUcesnici() {
        try {
            List<AbstractObjekat> ucesnici = Kontroler.vratiInstancu().ucitajUcesnike();
            mtucesnici = new ModelTabeleUcesnici(ucesnici);
            tblUcesnici.setModel(mtucesnici);
        } catch (Exception ex) {
            Logger.getLogger(DodajIzmeniUcesnika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void validirajIPostaviVrednosti(Kurs kurs) throws Exception {

        if (kurs == null) {
            throw new ValidacijaException("Morate odabrati kurs!");
        }

        List<AbstractObjekat> listaPredavaca = mtstavkepredavaci.getLista();
        if (listaPredavaca.isEmpty()) {
            throw new ValidacijaException("Morate uneti makar jednog predavača!");
        }

        List<AbstractObjekat> listaUcesnika = mtstavkeucesnici.getLista();
        if (listaUcesnika.isEmpty()) {
            throw new ValidacijaException("Morate uneti makar jednog učesnika!");
        }

        grupa.setKurs(kurs);
        grupa.setNaziv(txtNaziv.getText());
        grupa.setListaPredavaca((ArrayList<AbstractObjekat>) listaPredavaca);
        grupa.setListaUcesnika((ArrayList<AbstractObjekat>) listaUcesnika);
        grupa.setMenadzer(ulogovaniMenadzer);
    }

    private void srediFormu(Grupa grupa) {

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        srediFormu();
        txtGrupaID.setText(String.valueOf(grupa.getGrupaID()));
        txtMenadzer.setText(grupa.getMenadzer().toString());
        txtDatumOd.setText(sdf.format(grupa.getDatumOd()));
        cmbKursevi.setSelectedItem(grupa.getKurs()); //dodato naziv

        mtstavkepredavaci.setLista(grupa.getListaPredavaca());
        mtstavkepredavaci.popuniOriginalnuListu(grupa.getListaPredavaca());
        mtstavkepredavaci.fireTableDataChanged();

        mtstavkeucesnici.setLista(grupa.getListaUcesnika());
        mtstavkeucesnici.popuniOriginalnuListu(grupa.getListaUcesnika());
        mtstavkeucesnici.fireTableDataChanged();
    }

    private List<AbstractObjekat> napraviListuPredavaca() {
        List<AbstractObjekat> listaZaSlanje = new ArrayList<>(); 
        List<AbstractObjekat> originalnaLista = mtstavkepredavaci.getOriginalnaLista();
        List<AbstractObjekat> listaStavki = mtstavkepredavaci.getLista(); 

        for (AbstractObjekat ao : originalnaLista) {
            GrupaStavkaDodatiPredavaci originalnaStavka = (GrupaStavkaDodatiPredavaci) ao;
            boolean obrisana = true; 
            for (AbstractObjekat ao1 : listaStavki) { 
                GrupaStavkaDodatiPredavaci stavka = (GrupaStavkaDodatiPredavaci) ao1;
                if (originalnaStavka.getPredavac().equals(stavka.getPredavac())) { 
                    obrisana = false;
                    break;
                }
            }

            if (obrisana) { 
                originalnaStavka.setStanje("obrisana");
                listaZaSlanje.add(originalnaStavka);
            }
        }
        listaZaSlanje.addAll(listaStavki); 
        return listaZaSlanje;

    }
    

    private List<AbstractObjekat> napraviListuUcesnika() {
        List<AbstractObjekat> listaZaSlanje = new ArrayList<>(); 
        List<AbstractObjekat> originalnaLista = mtstavkeucesnici.getOriginalnaLista();
        List<AbstractObjekat> listaStavki = mtstavkeucesnici.getLista();

        for (AbstractObjekat ao : originalnaLista) { 
            GrupaStavkaDodatiUcesnici originalnaStavka = (GrupaStavkaDodatiUcesnici) ao; 
            boolean obrisana = true;
            for (AbstractObjekat ao1 : listaStavki) {
                GrupaStavkaDodatiUcesnici stavka = (GrupaStavkaDodatiUcesnici) ao1;
                if (originalnaStavka.getUcesnik().equals(stavka.getUcesnik())) {
                    obrisana = false;
                    break;
                }
            }
            if (obrisana) {
                originalnaStavka.setStanje("obrisana");
                listaZaSlanje.add(originalnaStavka);
            }
        }
        listaZaSlanje.addAll(listaStavki);
        return listaZaSlanje;

    }

}
